/* ──────────────────────────────────────────────────────────────────────────
   TOKEN MERIDIAN · data layer
   ----------------------------------------------------------------------------
   This is the ONLY file you touch to wire in real numbers.

   Right now it returns realistic sample data. To show your real Claude usage,
   replace the body of `getUsage()` so it returns the same shape — for example
   by fetching a JSON file you generate from Anthropic's Admin Usage & Cost API
   (see scripts/fetch-usage.mjs and README.md).

   The shape is intentionally small and stable. Keep these keys and the UI
   keeps working.
   ────────────────────────────────────────────────────────────────────────── */

// Per-model pricing ($ per 1M tokens) — handy if you later compute cost yourself.
const PRICING = {
  "Opus 4.8":   { input: 5,  output: 25 },
  "Sonnet 4.6": { input: 3,  output: 15 },
  "Haiku 4.5":  { input: 1,  output: 5  },
};

// Deterministic pseudo-random so the demo looks alive but never jitters on reload.
function seeded(seed) {
  let s = seed % 2147483647;
  if (s <= 0) s += 2147483646;
  return () => (s = (s * 16807) % 2147483647) / 2147483647;
}

function buildDemoData() {
  const rnd = seeded(424242);
  const today = new Date();

  // 14 days of usage, trending gently upward with a weekly dip on weekends.
  const days = [];
  for (let i = 13; i >= 0; i--) {
    const d = new Date(today);
    d.setDate(today.getDate() - i);
    const weekday = d.getDay(); // 0 Sun … 6 Sat
    const weekend = weekday === 0 || weekday === 6;
    const trend = 1 + (13 - i) * 0.045;
    const base = (weekend ? 0.45 : 1) * (1.6e6) * trend;
    const tokens = Math.round(base * (0.78 + rnd() * 0.5));
    days.push({
      date: d.toISOString().slice(0, 10),
      label: d.toLocaleDateString("en-US", { weekday: "short" }),
      tokens,
    });
  }

  const totalTokens = days.reduce((a, d) => a + d.tokens, 0);

  // How the spend splits across models.
  const models = [
    { name: "Opus 4.8",   share: 0.58, tint: "lime" },
    { name: "Sonnet 4.6", share: 0.31, tint: "teal" },
    { name: "Haiku 4.5",  share: 0.11, tint: "coral" },
  ].map((m) => {
    const tokens = Math.round(totalTokens * m.share);
    // rough blended cost using a 70/30 input:output mix
    const p = PRICING[m.name];
    const cost = (tokens / 1e6) * (p.input * 0.7 + p.output * 0.3);
    return { ...m, tokens, cost };
  });

  const totalCost = models.reduce((a, m) => a + m.cost, 0);

  // Token-type breakdown (drives the donut).
  const tokenTypes = [
    { name: "Input",        value: 0.41, tint: "teal"  },
    { name: "Output",       value: 0.23, tint: "lime"  },
    { name: "Cache read",   value: 0.30, tint: "coral" },
    { name: "Cache write",  value: 0.06, tint: "muted" },
  ];

  return {
    updatedAt: today.toISOString(),
    isDemo: true,
    kpis: {
      tokens: totalTokens,
      cost: totalCost,
      requests: 18420 + Math.round(rnd() * 800),
      cacheHitRate: 0.71, // share of input served from cache
    },
    days,
    models,
    tokenTypes,
  };
}

/**
 * Returns a Promise of the usage payload.
 *
 * REAL DATA: this first tries to load ./usage.json (your real numbers,
 * generated by one of the scripts in /scripts — see README). The moment that
 * file exists in the repo, the page shows your real tokens with no code change.
 * Until then, it falls back to the sample data so the page is never blank.
 */
async function getUsage() {
  try {
    const res = await fetch("./usage.json", { cache: "no-store" });
    if (res.ok) {
      const real = await res.json();
      real.isDemo = false;
      return real;
    }
  } catch (_) {
    /* no usage.json yet — fall through to sample data */
  }
  // tiny delay so the "computing…" animation has a moment to breathe
  await new Promise((r) => setTimeout(r, 650));
  return buildDemoData();
}

window.TokenMeridian = { getUsage };
